export default [
  {
    id: "Q1",
    title: "Q1 - HTML",
    type: "Graded Quiz",
    points: "100",
    assignment_group: "Quizzes",
    shuffle_answers: "Yes",
    time_limit: "20",
    multiple_attempts: "no",
    show_correct: "Immediately",
    access_code: "abcd",
    one_question: "Yes",
    webcam: "No",
    lock_question: "No",
    due_date: "2024-03-05",
    available_date: "2024-02-04",
    until_date: "2024-03-05",
    question_count: "11 Questions",
    course: "CS101",
    published: false,
  },
  {
    id: "Q2",
    title: "Q2 - CSS",
    type: "Practice Quiz",
    points: "90",
    assignment_group: "Exams",
    shuffle_answers: "Yes",
    time_limit: "30",
    multiple_attempts: "no",
    show_correct: "Immediately",
    access_code: "abcd",
    one_question: "Yes",
    webcam: "No",
    lock_question: "No",
    due_date: "2024-05-04",
    available_date: "2024-02-04",
    until_date: "2024-05-04",
    course: "CS101",
    question_count: "8 Questions",
    published: false,
  },
  {
    id: "Q3",
    title: "Q3 - Mongo",
    type: "Graded Survey",
    points: "40",
    assignment_group: "Assignments",
    shuffle_answers: "Yes",
    time_limit: "90",
    multiple_attempts: "no",
    show_correct: "Immediately",
    access_code: "abcd",
    one_question: "Yes",
    webcam: "No",
    lock_question: "No",
    due_date: "2024-05-06",
    available_date: "2024-05-04",
    until_date: "2024-05-06",
    course: "CS101",
    question_count: "9 Questions",
    published: false,
  },
  {
    id: "Q4",
    title: "Q4 - Node",
    type: "Ungraded Survey",
    points: "65",
    assignment_group: "Project",
    shuffle_answers: "Yes",
    time_limit: "40",
    multiple_attempts: "no",
    show_correct: "Immediately",
    access_code: "abcd",
    one_question: "Yes",
    webcam: "No",
    lock_question: "No",
    due_date: "2024-03-04",
    available_date: "2024-02-04",
    until_date: "2024-05-04",
    course: "CS101",
    question_count: "6 Questions",
    published: false,
  },
];
